flags: {}
extra-deps:
resolver: lts-8.13
packages:
  - '.'
  - location:
      git: https://github.com/ekmett/bound
      commit: 32e513ff564bbe1d0f2c0265abfc63d07b6f50c3
    extra-dep: true
nix:
  packages:
    - ncurses
