author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - MonoLocalBinds
  - NamedFieldPuns
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications

dependencies:
  - base
  - data-default
  - lens
  - megaparsec       >= 8.0
  - polysemy
  - polysemy-plugin
  - QuickCheck
  - smallcheck
  - string-qq
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-smallcheck

executables:
  chick-server:
    main: Main.hs
    source-dirs: exec
    dependencies:
      - chick

ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Wall
  - -Werror

library:

  dependencies:
    - adjunctions
    - aeson
    - bound
    - bytestring
    - comonad
    - containers
    - convertible
    - directory
    - either
    - extra
    - free
    - gdiff
    - ghc
    - GenericPretty
    - hslogger
    - language-ocaml ^>= 0.2.2
    - lens
    - MissingH
    - monad-loops
    - mtl
    - network
    - parser-combinators
    - prettyprinter
    - process
    - random
    - snap           ^>= 1.1.1.0
    - snap-core
    - snap-server
    - text
    - time
    - utility-ht
    - unordered-containers
    - utf8-string

  exposed-modules:
    - Diff.Atom
    - Diff.ConcatMap
    - Diff.Constructor
    - Diff.Eliminator
    - Diff.Guess.Constructor
    - Diff.Guess.Inductive
    - Diff.Guess.Node
    - Diff.Guess.Script
    - Diff.Guess.Term
    - Diff.Inductive
    - Diff.List
    - Diff.Motive
    - Diff.Script
    - Diff.Term
    - Examples.Diff.SoftwareFoundations
    - Examples.Term
    - Examples.Utils
    - Inductive.Eliminator
    - Inductive.Inductive
    - Inductive.Motive
    - Language
    - Notations
    - Parsing
    - Parsing.Inductive
    - Parsing.Unsafe
    - Precedence
    - PrettyPrinting.Chick
    - PrettyPrinting.PrettyPrintable
    - PrettyPrinting.Term
    - Repair.Benchmark
    - Script
    - Server.Server
    - StandardLibrary
    - StandardLibraryDiff
    - Term.Raw
    - Term.Term
    - Term.Universe
    - Term.Variable
    - Utils

  other-modules:
    - Bound.ScopeT
    - Definition
    - DefinitionObjectKind
    - DictMetaOut
    - Diff.Binder
    - Diff.Guess.Atom
    - Diff.Guess.BottomUp
    - Diff.Guess.HIList
    - Diff.Guess.Mapping
    - Diff.Guess.TopDown
    - Diff.Guess.Vernacular
    - Diff.GlobalDeclaration
    - Diff.GlobalEnvironment
    - Diff.ListFold
    - Diff.ListFoldLeft
    - Diff.ListFoldRight
    - Diff.ListFoldUtils
    - Diff.LocalContext
    - Diff.LocalDeclaration
    - Diff.Maybe
    - Diff.Pair
    - Diff.Triple
    - Diff.Utils
    - Diff.Variable
    - Diff.Vernacular
    - Examples.Inductive
    - FromOCaml
    - Goal
    - Inductive.Utils
    - Parsing.Types
    - Parsing.Chick.Utils
    - Parsing.Script
    - Parsing.Utils
    - Parsing.Vernacular
    - PrettyPrinting.Chick.Binder
    - PrettyPrinting.Chick.Constructor
    - PrettyPrinting.Chick.Declaration
    - PrettyPrinting.Chick.Definition
    - PrettyPrinting.Chick.DefinitionObjectKind
    - PrettyPrinting.Chick.LocalContext
    - PrettyPrinting.Chick.LocalDeclaration
    - PrettyPrinting.Chick.GlobalEnvironment
    - PrettyPrinting.Chick.GlobalDeclaration
    - PrettyPrinting.Chick.Inductive
    - PrettyPrinting.Chick.List
    - PrettyPrinting.Chick.Pair
    - PrettyPrinting.Chick.Script
    - PrettyPrinting.Chick.Term
    - PrettyPrinting.Chick.Triple
    - PrettyPrinting.Chick.Unit
    - PrettyPrinting.Chick.Universe
    - PrettyPrinting.Chick.Variable
    - PrettyPrinting.Chick.Vernacular
    - PrettyPrinting.PrettyPrintableAnnotated
    - PrettyPrinting.PrettyPrintableUnannotated
    - PrettyPrinting.Universe
    - PrettyPrinting.Utils
    - Repair.Inductive
    - Repair.Script
    - Repair.State
    - Repair.Term
    - Repair.Term.Argument
    - Repair.Term.Branch
    - Repair.Utils
    - Repair.Vernacular
    - Server.Chick
    - Server.ChickHandler
    - Server.Session
    - Snap.Extras.JSON
    - Term.AlphaEquivalence
    - Term.AlphaRenaming
    - Term.Binder
    - Term.Diff
    - Term.Free
    - Term.Fresh
    - Term.TypeChecked
    - Term.TypeErrored
    - ToOCaml
    - TypeCheckingFailure
    - Typing.GlobalDeclaration
    - Typing.GlobalEnvironment
    - Typing.LocalContext
    - Typing.LocalDeclaration
    - Typing.Utils
    - Vernacular
    - WellFormed
    - Work

  source-dirs: lib

license: BSD3

name: chick

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - chick
    other-modules:
      - Diff.ConcatMap.Test
      - Diff.Eliminator.Test
      - Diff.Guess.Constructor.Test
      - Diff.Guess.Term.Test
      - Diff.Guess.Inductive.Test
      - Diff.Guess.Script.Test
      - Diff.Guess.Vernacular.Test
      - Diff.Motive.Test
      - Inductive.Eliminator.Test
      - Inductive.Inductive.Test
      - Parsing.Inductive.Test
      - StandardLibraryDiff.Test
      - Term.Term.Test
      - TestUtils

version: 0.1.0
