author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - MonoLocalBinds
  - NamedFieldPuns
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax

dependencies:
  - base            ^>= 4.13.0.0
  - bound           ^>= 2.0.1
  - data-default    ^>= 0.7.1.1
  - directory       ^>= 1.3.6.0
  - language-ocaml  ^>= 0.2.2
  - megaparsec      ^>= 8.0
  - polysemy        ^>= 1.3.0.0
  - polysemy-plugin ^>= 0.2.5.0
  - QuickCheck      ^>= 2.13.2
  - smallcheck      ^>= 1.1.5
  - string-qq       ^>= 0.0.4
  # These are test dependencies, but for nix, I must put them here...
  - filepath         ^>= 1.4.2.1
  - tasty            ^>= 1.2.3
  - tasty-hunit      ^>= 0.10.0.2
  - tasty-quickcheck ^>= 0.10.1.1
  - tasty-smallcheck ^>= 0.8.1

executables:
  chick-server:
    main: Main.hs
    source-dirs: exec
    dependencies:
      - chick

ghc-options:
  # temporarily disabled: currently breaks hie
  # - -fplugin=Polysemy.Plugin
  - -Wall
  - -Werror

library:

  dependencies:
    - adjunctions          ^>= 4.4
    - aeson                ^>= 1.4.6.0
    - bytestring           ^>= 0.10.10.0
    - comonad              ^>= 5.0.6
    - containers           ^>= 0.6.2.1
    - convertible          ^>= 1.1.1.0
    - either               ^>= 5.0.1.1
    - extra                ^>= 1.6.21
    - free                 ^>= 5.1.3
    - gdiff                ^>= 1.1
    - ghc                  ^>= 8.8.3
    - GenericPretty        ^>= 1.2.2
    - hslogger             ^>= 1.3.1.0
    - lens                 ^>= 4.18.1
    - MissingH             ^>= 1.4.2.0
    - monad-loops          ^>= 0.4.3
    - mtl                  ^>= 2.2.2
    - network              ^>= 3.1.1.1
    - parser-combinators   ^>= 1.2.1
    - prettyprinter        ^>= 1.6.1
    - process              ^>= 1.6.8.0
    - random               ^>= 1.1
    - snap                 ^>= 1.1.1.0
    - snap-core            ^>= 1.0.4.1
    - snap-server          ^>= 1.1.1.1
    - text                 ^>= 1.2.4.0
    - time                 ^>= 1.9.3
    - utility-ht           ^>= 0.0.14
    - unordered-containers ^>= 0.2.10.0
    - utf8-string          ^>= 1.0.1.1

  exposed-modules:
    - Diff.Atom
    - Diff.ConcatMap
    - Diff.Constructor
    - Diff.Eliminator
    - Diff.Guess.Constructor
    - Diff.Guess.Inductive
    - Diff.Guess.Node
    - Diff.Guess.Script
    - Diff.Guess.Term
    - Diff.Inductive
    - Diff.List
    - Diff.Motive
    - Diff.Script
    - Diff.Term
    - Examples.Diff.SoftwareFoundations
    - Examples.Term
    - Examples.Utils
    - FromOCaml
    - Inductive.Eliminator
    - Inductive.Inductive
    - Inductive.Motive
    - Language
    - Notations
    - Parsing
    - Parsing.Inductive
    - Parsing.Unsafe
    - Precedence
    - PrettyPrinting.Chick
    - PrettyPrinting.PrettyPrintable
    - PrettyPrinting.PrettyPrintableUnannotated
    - PrettyPrinting.Term
    - Repair.Benchmark
    - Script
    - Server.Server
    - StandardLibrary
    - StandardLibraryDiff
    - Term.Raw
    - Term.Term
    - Term.Universe
    - Term.Variable
    - Utils

  other-modules:
    - Bound.ScopeT
    - Definition
    - DefinitionObjectKind
    - DictMetaOut
    - Diff.Binder
    - Diff.Guess.Atom
    - Diff.Guess.BottomUp
    - Diff.Guess.HIList
    - Diff.Guess.Mapping
    - Diff.Guess.TopDown
    - Diff.Guess.Vernacular
    - Diff.GlobalDeclaration
    - Diff.GlobalEnvironment
    - Diff.ListFold
    - Diff.ListFoldLeft
    - Diff.ListFoldRight
    - Diff.ListFoldUtils
    - Diff.LocalContext
    - Diff.LocalDeclaration
    - Diff.Maybe
    - Diff.Pair
    - Diff.Triple
    - Diff.Utils
    - Diff.Variable
    - Diff.Vernacular
    - Examples.Inductive
    - Goal
    - Inductive.Utils
    - Parsing.Types
    - Parsing.Chick.Utils
    - Parsing.Script
    - Parsing.Utils
    - Parsing.Vernacular
    - PrettyPrinting.Chick.Binder
    - PrettyPrinting.Chick.Constructor
    - PrettyPrinting.Chick.Declaration
    - PrettyPrinting.Chick.Definition
    - PrettyPrinting.Chick.DefinitionObjectKind
    - PrettyPrinting.Chick.LocalContext
    - PrettyPrinting.Chick.LocalDeclaration
    - PrettyPrinting.Chick.GlobalEnvironment
    - PrettyPrinting.Chick.GlobalDeclaration
    - PrettyPrinting.Chick.Inductive
    - PrettyPrinting.Chick.List
    - PrettyPrinting.Chick.Pair
    - PrettyPrinting.Chick.Script
    - PrettyPrinting.Chick.Term
    - PrettyPrinting.Chick.Triple
    - PrettyPrinting.Chick.Unit
    - PrettyPrinting.Chick.Universe
    - PrettyPrinting.Chick.Variable
    - PrettyPrinting.Chick.Vernacular
    - PrettyPrinting.PrettyPrintableAnnotated
    - PrettyPrinting.Universe
    - PrettyPrinting.Utils
    - Repair.Inductive
    - Repair.Script
    - Repair.State
    - Repair.Term
    - Repair.Term.Argument
    - Repair.Term.Branch
    - Repair.Utils
    - Repair.Vernacular
    - Server.Chick
    - Server.ChickHandler
    - Server.Session
    - Snap.Extras.JSON
    - Term.AlphaEquivalence
    - Term.AlphaRenaming
    - Term.Binder
    - Term.Diff
    - Term.Free
    - Term.Fresh
    - Term.TypeChecked
    - Term.TypeErrored
    - ToOCaml
    - TypeCheckingFailure
    - Typing.GlobalDeclaration
    - Typing.GlobalEnvironment
    - Typing.LocalContext
    - Typing.LocalDeclaration
    - Typing.Utils
    - Vernacular
    - WellFormed
    - Work

  source-dirs: lib

license: BSD3

name: chick

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - chick
    other-modules:
      - Diff.ConcatMap.Test
      - Diff.Eliminator.Test
      - Diff.Guess.Constructor.Test
      - Diff.Guess.Term.Test
      - Diff.Guess.Inductive.Test
      - Diff.Guess.Script.Test
      - Diff.Guess.Vernacular.Test
      - Diff.Motive.Test
      - Inductive.Eliminator.Test
      - Inductive.Inductive.Test
      - Parsing.Inductive.Test
      - StandardLibraryDiff.Test
      - Term.Term.Test
      - TestUtils

version: 0.1.0
