flags: {}

extra-deps:
  - aeson-1.3.1.1
  - extensible-effects-3.0.0.0
  - free-5
  - gdiff-1.1
  - heist-1.1
  - map-syntax-0.3
  - snap-1.1.1.0

resolver: lts-11.11

packages:
  - '.'
  - location:
      git: https://github.com/ekmett/bound
      commit: 32e513ff564bbe1d0f2c0265abfc63d07b6f50c3
    extra-dep: true
  - location:
      git: https://github.com/IxpertaSolutions/freer-effects
      commit: 39a7e62cc049d43d36ece4ac24ba19e545f0b726
    extra-dep: true
  - location:
      git: https://github.com/Ptival/language-ocaml
      commit: 46d35d0359790770a657967ca6ef0b33ca2d40f2
    extra-dep: true
