Reserved Notation "Γ ⊢ x ⇓a v"     (at level 70).
Reserved Notation "Γ ⊢ a ⇒a v"     (at level 70).
Reserved Notation "Γ ⊢ a ⇒ v"      (at level 70).
Reserved Notation "g ⊢ e ↓args gs" (at level 70).
Reserved Notation "g ⊢ e ↓patt gs" (at level 70).
Reserved Notation "g ⊢ e ↓seq gs"  (at level 70).
Reserved Notation "g ⊢ e ↓v gs"    (at level 70).
Reserved Notation "g ⊢ e ↓vx gs"   (at level 70).
Reserved Notation "g ⊢ e ↓x gs"    (at level 70).
Reserved Notation "g ⊢ e ⇓ r"      (at level 70).
